# Generated by Django 5.1.3 on 2025-02-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('dikutip_oleh', models.IntegerField(default=0)),
                ('tahun', models.IntegerField()),
                ('link_publikasi', models.URLField()),
            ],
        ),
    ]
