# Generated by Django 5.1.3 on 2025-02-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='pkm_images/')),
                ('tanggal', models.DateField()),
            ],
        ),
    ]
