# Generated by Django 5.1.3 on 2025-02-20 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pkm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='research_images/')),
                ('tanggal', models.DateField()),
                ('metodologi', models.TextField()),
                ('hasil', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='research_gallery/')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='myapp.research')),
            ],
        ),
    ]
