# Generated by Django 5.1.3 on 2025-02-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_research_researchgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='hasil',
            field=models.TextField(help_text='Hasil penelitian dalam format poin-poin'),
        ),
        migrations.AlterField(
            model_name='research',
            name='metodologi',
            field=models.TextField(help_text='Metodologi dalam format poin-poin'),
        ),
    ]
