# Generated by Django 5.1.3 on 2025-02-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_research_hasil_alter_research_metodologi'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='status',
            field=models.CharField(choices=[('on_progress', 'On Progress'), ('done', 'Done')], default='on_progress', max_length=20),
        ),
    ]
