# Generated by Django 5.1.1 on 2025-02-23 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_job_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='teaching/')),
                ('forms_of_learning', models.TextField(blank=True, null=True)),
                ('learning_methods', models.TextField(blank=True, null=True)),
                ('rps_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpl_code', models.CharField(max_length=50)),
                ('cpmk_code', models.CharField(max_length=50)),
                ('cpmk_statement', models.TextField()),
                ('sub_cpmk_statement', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='myapp.teachingsubject')),
            ],
        ),
    ]
