# Generated by Django 5.1.1 on 2025-02-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_teachingsubject_learningoutcome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningoutcome',
            options={'ordering': ['cpmk_code']},
        ),
        migrations.AlterModelOptions(
            name='teachingsubject',
            options={'ordering': ['title']},
        ),
        migrations.AlterUniqueTogether(
            name='learningoutcome',
            unique_together={('subject', 'cpmk_code')},
        ),
    ]
