# Generated by Django 5.1.1 on 2025-02-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_learningoutcome_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='subjects/')),
                ('rps_file', models.FileField(blank=True, null=True, upload_to='rps_files/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LearningOutcome',
        ),
        migrations.DeleteModel(
            name='TeachingSubject',
        ),
    ]
