# Generated by Django 5.1.1 on 2025-02-23 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_subject_image_subject_course_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='cpl_table',
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpl_code', models.CharField(blank=True, max_length=100, null=True)),
                ('cpmk_code', models.CharField(blank=True, max_length=100, null=True)),
                ('cpmk_statement', models.TextField(blank=True, null=True)),
                ('sub_cpmk_statement', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='myapp.subject')),
            ],
        ),
    ]
