# Generated by Django 5.1.1 on 2025-02-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_subject_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course_description',
        ),
    ]
