# Generated by Django 5.1.1 on 2025-02-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_subject_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
