<<<<<<< HEAD
# Generated by Django 5.1.3 on 2025-02-25 13:35
=======
# Generated by Django 5.1.1 on 2025-02-26 03:05
>>>>>>> 6d890fd7617acb224d70f105e4c45f62903ec8f5

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_subject_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('community_service', 'Community Service'), ('research', 'Research')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.pkm')),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.research')),
            ],
        ),
    ]
