# Generated by Django 5.1.3 on 2025-02-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_pkm_objectives_pkm_significance_alter_pkm_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkm',
            name='tujuan',
            field=models.TextField(default=''),
        ),
    ]
