# Generated by Django 5.1.3 on 2025-02-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_pkm_tujuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkm',
            name='status',
            field=models.CharField(choices=[('on_progress', 'On Progress'), ('done', 'Done')], default='on_progress', max_length=20),
        ),
    ]
