# Generated by Django 5.1.1 on 2025-03-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_pkm_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='qualifications',
            new_name='qualification_1',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='responsibilities',
            new_name='qualification_2',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='skills',
            new_name='qualification_3',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='working_time',
            new_name='responsibilities_1',
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities_3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skill_1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skill_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skill_3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='working_time_1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='working_time_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
