# Generated by Django 5.1.1 on 2025-03-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_qualifications_job_qualification_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='qualification_1',
            new_name='qualifications',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='qualification_2',
            new_name='responsibilities',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='qualification_3',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='responsibilities_1',
            new_name='working_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='responsibilities_2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='responsibilities_3',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='job',
            name='working_time_1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='working_time_2',
        ),
    ]
